/**
 * ProofKind — Taxonomy of deductive proof steps.
 */

export const PROOF_KINDS = Object.freeze({
    DIRECT: 'DIRECT',
    DERIVED: 'DERIVED',
    PATH_CONDITION: 'PATH_CONDITION',
    TYPE_NARROWING: 'TYPE_NARROWING',
    RANGE_NARROWING: 'RANGE_NARROWING',
    SSA_DEFINITION: 'SSA_DEFINITION',
    DATAFLOW_ORIGIN: 'DATAFLOW_ORIGIN',
    CONSTRAINT_COMBINATION: 'CONSTRAINT_COMBINATION',
    FUNCTION_SUMMARY: 'FUNCTION_SUMMARY',
    INVARIANT: 'INVARIANT',
    CONTRACT: 'CONTRACT',
});
