/**
 * ApprovalKind.js
 * Categories of operations requiring explicit human approval.
 */

export const ApprovalKind = Object.freeze({
  HIGH_RISK_REPAIR: 'HIGH_RISK_REPAIR',
  SECURITY_MITIGATION: 'SECURITY_MITIGATION',
  PUBLIC_API_CHANGE: 'PUBLIC_API_CHANGE',
  ARCHITECTURE_TRANSFORMATION: 'ARCHITECTURE_TRANSFORMATION',
  PRODUCTION_RELEASE: 'PRODUCTION_RELEASE',
  EMERGENCY_OVERRIDE: 'EMERGENCY_OVERRIDE'
});
