/**
 * CapabilityKind.js
 * Comprehensive enum of all 20+ capabilities supported by the ProViz verification ecosystem.
 */

export const CapabilityKind = Object.freeze({
  STATIC_ANALYSIS: 'STATIC_ANALYSIS',
  SYMBOLIC_REASONING: 'SYMBOLIC_REASONING',
  TEST_GENERATION: 'TEST_GENERATION',
  CONCOLIC_EXECUTION: 'CONCOLIC_EXECUTION',
  PROGRAM_REPAIR: 'PROGRAM_REPAIR',
  MUTATION_ANALYSIS: 'MUTATION_ANALYSIS',
  PROBABILISTIC_ANALYSIS: 'PROBABILISTIC_ANALYSIS',
  PLANNING: 'PLANNING',
  ORCHESTRATION: 'ORCHESTRATION',
  FEDERATION: 'FEDERATION',
  KNOWLEDGE_REASONING: 'KNOWLEDGE_REASONING',
  SEMANTIC_ANALYSIS: 'SEMANTIC_ANALYSIS',
  EVOLUTION: 'EVOLUTION',
  SECURITY: 'SECURITY',
  PERFORMANCE: 'PERFORMANCE',
  CONCURRENCY: 'CONCURRENCY',
  CONTINUOUS_VERIFICATION: 'CONTINUOUS_VERIFICATION',
  PROJECT_INTELLIGENCE: 'PROJECT_INTELLIGENCE',
  GOVERNANCE: 'GOVERNANCE',
  CERTIFICATION: 'CERTIFICATION'
});
