/**
 * EscalationReason.js
 * Precise causes triggering human escalation in ProViz OS.
 */

export const EscalationReason = Object.freeze({
  HIGH_RISK_REPAIR: 'HIGH_RISK_REPAIR',
  AMBIGUOUS_ROOT_CAUSE: 'AMBIGUOUS_ROOT_CAUSE',
  CONFLICTING_EVIDENCE: 'CONFLICTING_EVIDENCE',
  SECURITY_SENSITIVE_CHANGE: 'SECURITY_SENSITIVE_CHANGE',
  SIGNIFICANT_API_CHANGE: 'SIGNIFICANT_API_CHANGE',
  ARCHITECTURE_BOUNDARY_CHANGE: 'ARCHITECTURE_BOUNDARY_CHANGE',
  UNBOUNDED_VERIFICATION_REQUIREMENT: 'UNBOUNDED_VERIFICATION_REQUIREMENT',
  INSUFFICIENT_EVIDENCE: 'INSUFFICIENT_EVIDENCE',
  FAILED_ROLLBACK: 'FAILED_ROLLBACK',
  GOVERNANCE_POLICY_CONFLICT: 'GOVERNANCE_POLICY_CONFLICT'
});
