/**
 * VerificationEventKind.js
 * Comprehensive enum of all immutable events across ProViz OS lifecycle.
 */

export const VerificationEventKind = Object.freeze({
  PROJECT_LOADED: 'PROJECT_LOADED',
  SOURCE_CHANGED: 'SOURCE_CHANGED',
  SEMANTIC_CHANGE_DETECTED: 'SEMANTIC_CHANGE_DETECTED',
  VERIFICATION_OBLIGATION_CREATED: 'VERIFICATION_OBLIGATION_CREATED',
  VERIFICATION_STARTED: 'VERIFICATION_STARTED',
  VERIFICATION_COMPLETED: 'VERIFICATION_COMPLETED',
  FINDING_CREATED: 'FINDING_CREATED',
  FAILURE_CLUSTERED: 'FAILURE_CLUSTERED',
  ROOT_CAUSE_IDENTIFIED: 'ROOT_CAUSE_IDENTIFIED',
  REPAIR_PROPOSED: 'REPAIR_PROPOSED',
  REPAIR_APPROVED: 'REPAIR_APPROVED',
  REPAIR_REJECTED: 'REPAIR_REJECTED',
  REPAIR_APPLIED: 'REPAIR_APPLIED',
  ROLLBACK_STARTED: 'ROLLBACK_STARTED',
  ROLLBACK_COMPLETED: 'ROLLBACK_COMPLETED',
  GOVERNANCE_VIOLATION: 'GOVERNANCE_VIOLATION',
  ESCALATION_REQUIRED: 'ESCALATION_REQUIRED',
  CERTIFICATE_CREATED: 'CERTIFICATE_CREATED',
  PROJECT_STATE_CHANGED: 'PROJECT_STATE_CHANGED',
  RUNTIME_PAUSED: 'RUNTIME_PAUSED',
  RUNTIME_RESUMED: 'RUNTIME_RESUMED',
  SAFE_MODE_ENTERED: 'SAFE_MODE_ENTERED',
  SAFE_MODE_RECOVERED: 'SAFE_MODE_RECOVERED'
});
