export const CancellationReason = Object.freeze({
  GOAL_SATISFIED: 'GOAL_SATISFIED',
  SUPERSEDED: 'SUPERSEDED',
  BUDGET_EXHAUSTED: 'BUDGET_EXHAUSTED',
  RESOURCE_PRESSURE: 'RESOURCE_PRESSURE',
  STALE: 'STALE',
  DUPLICATE: 'DUPLICATE',
  HIGHER_PRIORITY_TASK: 'HIGHER_PRIORITY_TASK',
  USER_REQUEST: 'USER_REQUEST'
});
