export const EvidenceMergePolicy = Object.freeze({
  APPEND: 'APPEND',
  RECONCILE: 'RECONCILE',
  DEDUPLICATE: 'DEDUPLICATE',
  PREFER_FORMAL: 'PREFER_FORMAL',
  PREFER_FRESH: 'PREFER_FRESH',
  PRESERVE_CONFLICT: 'PRESERVE_CONFLICT'
});
