export const ResourceKind = Object.freeze({
  CPU: 'CPU',
  MEMORY: 'MEMORY',
  TIME: 'TIME',
  PROCESS: 'PROCESS',
  THREAD: 'THREAD',
  DISK: 'DISK',
  NETWORK: 'NETWORK',
  SOLVER: 'SOLVER',
  TEST_EXECUTION: 'TEST_EXECUTION',
  SYMBOLIC_PATH: 'SYMBOLIC_PATH',
  MUTANT: 'MUTANT',
  CONTAINER: 'CONTAINER'
});
