export const VerificationTaskStatus = Object.freeze({
  QUEUED: 'QUEUED',
  READY: 'READY',
  RUNNING: 'RUNNING',
  COMPLETED: 'COMPLETED',
  PARTIALLY_COMPLETED: 'PARTIALLY_COMPLETED',
  FAILED: 'FAILED',
  CANCELLED: 'CANCELLED',
  BLOCKED: 'BLOCKED',
  RETRYING: 'RETRYING',
  STALE: 'STALE',
  SUPERSEDED: 'SUPERSEDED'
});
