export const VerificationTaskKind = Object.freeze({
  STATIC_VERIFICATION: 'STATIC_VERIFICATION',
  SYMBOLIC_ANALYSIS: 'SYMBOLIC_ANALYSIS',
  TEST_GENERATION: 'TEST_GENERATION',
  TEST_EXECUTION: 'TEST_EXECUTION',
  CONCOLIC_EXECUTION: 'CONCOLIC_EXECUTION',
  MUTATION_ANALYSIS: 'MUTATION_ANALYSIS',
  MUTANT_KILLING: 'MUTANT_KILLING',
  REPAIR_VALIDATION: 'REPAIR_VALIDATION',
  REGRESSION_ANALYSIS: 'REGRESSION_ANALYSIS',
  PROBABILISTIC_ANALYSIS: 'PROBABILISTIC_ANALYSIS',
  ANOMALY_REPRODUCTION: 'ANOMALY_REPRODUCTION',
  ORACLE_VALIDATION: 'ORACLE_VALIDATION',
  CONTRACT_VERIFICATION: 'CONTRACT_VERIFICATION',
  INVARIANT_VERIFICATION: 'INVARIANT_VERIFICATION',
  EVIDENCE_RECONCILIATION: 'EVIDENCE_RECONCILIATION'
});
