/**
 * ChangeKind — Enumeration of semantic change kinds supported in ProViz.
 */

export const CHANGE_KINDS = Object.freeze({
    // File level
    FILE_ADDED: 'FILE_ADDED',
    FILE_REMOVED: 'FILE_REMOVED',
    FILE_MODIFIED: 'FILE_MODIFIED',

    // Module & Import/Export
    MODULE_ADDED: 'MODULE_ADDED',
    MODULE_REMOVED: 'MODULE_REMOVED',
    MODULE_MODIFIED: 'MODULE_MODIFIED',
    IMPORT_ADDED: 'IMPORT_ADDED',
    IMPORT_REMOVED: 'IMPORT_REMOVED',
    IMPORT_CHANGED: 'IMPORT_CHANGED',
    EXPORT_ADDED: 'EXPORT_ADDED',
    EXPORT_REMOVED: 'EXPORT_REMOVED',
    EXPORT_CHANGED: 'EXPORT_CHANGED',

    // Symbol level
    SYMBOL_ADDED: 'SYMBOL_ADDED',
    SYMBOL_REMOVED: 'SYMBOL_REMOVED',
    SYMBOL_RENAMED: 'SYMBOL_RENAMED',
    SYMBOL_REBOUND: 'SYMBOL_REBOUND',

    // Function level
    FUNCTION_ADDED: 'FUNCTION_ADDED',
    FUNCTION_REMOVED: 'FUNCTION_REMOVED',
    FUNCTION_SIGNATURE_CHANGED: 'FUNCTION_SIGNATURE_CHANGED',
    FUNCTION_BODY_CHANGED: 'FUNCTION_BODY_CHANGED',
    FUNCTION_RETURN_CHANGED: 'FUNCTION_RETURN_CHANGED',

    // Statement level
    STATEMENT_ADDED: 'STATEMENT_ADDED',
    STATEMENT_REMOVED: 'STATEMENT_REMOVED',
    STATEMENT_MODIFIED: 'STATEMENT_MODIFIED',
    STATEMENT_MOVED: 'STATEMENT_MOVED',

    // Control flow
    CONTROL_FLOW_ADDED: 'CONTROL_FLOW_ADDED',
    CONTROL_FLOW_REMOVED: 'CONTROL_FLOW_REMOVED',
    BRANCH_CHANGED: 'BRANCH_CHANGED',
    LOOP_CHANGED: 'LOOP_CHANGED',
    EXCEPTION_FLOW_CHANGED: 'EXCEPTION_FLOW_CHANGED',

    // Dataflow
    DEFINITION_CHANGED: 'DEFINITION_CHANGED',
    USE_CHANGED: 'USE_CHANGED',
    DATA_DEPENDENCY_ADDED: 'DATA_DEPENDENCY_ADDED',
    DATA_DEPENDENCY_REMOVED: 'DATA_DEPENDENCY_REMOVED',
    ALIAS_CHANGED: 'ALIAS_CHANGED',
    MUTATION_BEHAVIOR_CHANGED: 'MUTATION_BEHAVIOR_CHANGED',

    // Type & Shape
    TYPE_CHANGED: 'TYPE_CHANGED',
    NULLABILITY_CHANGED: 'NULLABILITY_CHANGED',
    COLLECTION_SHAPE_CHANGED: 'COLLECTION_SHAPE_CHANGED',
    VALUE_RANGE_CHANGED: 'VALUE_RANGE_CHANGED',

    // Verification
    VERIFICATION_PROPERTY_ADDED: 'VERIFICATION_PROPERTY_ADDED',
    VERIFICATION_PROPERTY_REMOVED: 'VERIFICATION_PROPERTY_REMOVED',
    VERIFICATION_RESULT_CHANGED: 'VERIFICATION_RESULT_CHANGED',

    // Symbolic
    SYMBOLIC_PATH_ADDED: 'SYMBOLIC_PATH_ADDED',
    SYMBOLIC_PATH_REMOVED: 'SYMBOLIC_PATH_REMOVED',
    PATH_CONDITION_CHANGED: 'PATH_CONDITION_CHANGED',

    // Runtime Behavior
    RUNTIME_BEHAVIOR_CHANGED: 'RUNTIME_BEHAVIOR_CHANGED',
    EXCEPTION_BEHAVIOR_CHANGED: 'EXCEPTION_BEHAVIOR_CHANGED',
    RETURN_BEHAVIOR_CHANGED: 'RETURN_BEHAVIOR_CHANGED',
    STATE_MUTATION_CHANGED: 'STATE_MUTATION_CHANGED',

    // Test level
    TEST_COVERAGE_CHANGED: 'TEST_COVERAGE_CHANGED',
    TEST_EXPECTATION_CHANGED: 'TEST_EXPECTATION_CHANGED',
});
