/**
 * RegressionClassification — Taxonomy of behavioral comparison outcomes.
 */

export const REGRESSION_CLASSIFICATIONS = Object.freeze({
    NO_REGRESSION: 'NO_REGRESSION',
    EXPECTED_CHANGE: 'EXPECTED_CHANGE',
    UNEXPECTED_REGRESSION: 'UNEXPECTED_REGRESSION',
    NEW_FAILURE: 'NEW_FAILURE',
    FIXED_FAILURE: 'FIXED_FAILURE',
    BEHAVIOR_CHANGED: 'BEHAVIOR_CHANGED',
    EXCEPTION_CHANGED: 'EXCEPTION_CHANGED',
    RETURN_VALUE_CHANGED: 'RETURN_VALUE_CHANGED',
    STATE_CHANGED: 'STATE_CHANGED',
    COVERAGE_CHANGED: 'COVERAGE_CHANGED',
    UNRESOLVED: 'UNRESOLVED',
});
