/**
 * EvidenceKind — Taxonomy of evidence sources spanning static, formal, dynamic, and exploration layers.
 */

export const EVIDENCE_KINDS = Object.freeze({
    STATIC_PROOF: 'STATIC_PROOF',
    STATIC_ANALYSIS: 'STATIC_ANALYSIS',
    RUNTIME_OBSERVATION: 'RUNTIME_OBSERVATION',
    TEST_ASSERTION: 'TEST_ASSERTION',
    WATCH_OBSERVATION: 'WATCH_OBSERVATION',
    SYMBOLIC_PROOF: 'SYMBOLIC_PROOF',
    SYMBOLIC_COUNTEREXAMPLE: 'SYMBOLIC_COUNTEREXAMPLE',
    CONCOLIC_EXECUTION: 'CONCOLIC_EXECUTION',
    MUTATION_RESULT: 'MUTATION_RESULT',
    REPAIR_VALIDATION: 'REPAIR_VALIDATION',
    REGRESSION_RESULT: 'REGRESSION_RESULT',
    SPECIFICATION_RESULT: 'SPECIFICATION_RESULT',
    ORACLE_RESULT: 'ORACLE_RESULT',
    METAMORPHIC_RESULT: 'METAMORPHIC_RESULT',
    EXPLORATION_RESULT: 'EXPLORATION_RESULT',
    USER_ASSERTION: 'USER_ASSERTION',
    ENVIRONMENT_OBSERVATION: 'ENVIRONMENT_OBSERVATION',
});

export class EvidenceKind {
    static STATIC_PROOF = EVIDENCE_KINDS.STATIC_PROOF;
    static STATIC_ANALYSIS = EVIDENCE_KINDS.STATIC_ANALYSIS;
    static RUNTIME_OBSERVATION = EVIDENCE_KINDS.RUNTIME_OBSERVATION;
    static TEST_ASSERTION = EVIDENCE_KINDS.TEST_ASSERTION;
    static WATCH_OBSERVATION = EVIDENCE_KINDS.WATCH_OBSERVATION;
    static SYMBOLIC_PROOF = EVIDENCE_KINDS.SYMBOLIC_PROOF;
    static SYMBOLIC_COUNTEREXAMPLE = EVIDENCE_KINDS.SYMBOLIC_COUNTEREXAMPLE;
    static CONCOLIC_EXECUTION = EVIDENCE_KINDS.CONCOLIC_EXECUTION;
    static MUTATION_RESULT = EVIDENCE_KINDS.MUTATION_RESULT;
    static REPAIR_VALIDATION = EVIDENCE_KINDS.REPAIR_VALIDATION;
    static REGRESSION_RESULT = EVIDENCE_KINDS.REGRESSION_RESULT;
    static SPECIFICATION_RESULT = EVIDENCE_KINDS.SPECIFICATION_RESULT;
    static ORACLE_RESULT = EVIDENCE_KINDS.ORACLE_RESULT;
    static METAMORPHIC_RESULT = EVIDENCE_KINDS.METAMORPHIC_RESULT;
    static EXPLORATION_RESULT = EVIDENCE_KINDS.EXPLORATION_RESULT;
    static USER_ASSERTION = EVIDENCE_KINDS.USER_ASSERTION;
    static ENVIRONMENT_OBSERVATION = EVIDENCE_KINDS.ENVIRONMENT_OBSERVATION;

    static isValid(kind) {
        return Object.values(EVIDENCE_KINDS).includes(kind);
    }
}
