/**
 * EvidenceSource — Models the originating stage or subsystem that produced an evidence item.
 */

export const EVIDENCE_SOURCES = Object.freeze({
    STAGE_15_VERIFICATION: 'STAGE_15_VERIFICATION',
    STAGE_16_SYMBOLIC: 'STAGE_16_SYMBOLIC',
    STAGE_17_TESTING: 'STAGE_17_TESTING',
    STAGE_18_CONCOLIC: 'STAGE_18_CONCOLIC',
    STAGE_19_REPAIR: 'STAGE_19_REPAIR',
    STAGE_20_MUTATION: 'STAGE_20_MUTATION',
    STAGE_21_REGRESSION: 'STAGE_21_REGRESSION',
    STAGE_22_SPECIFICATION: 'STAGE_22_SPECIFICATION',
    STAGE_23_EXPLORATION: 'STAGE_23_EXPLORATION',
    STAGE_24_PROBABILISTIC: 'STAGE_24_PROBABILISTIC',
    RUNTIME_EXECUTION: 'RUNTIME_EXECUTION',
    TEST_EXECUTION: 'TEST_EXECUTION',
    USER_INTERACTION: 'USER_INTERACTION',
    ENVIRONMENT: 'ENVIRONMENT',
});

export class EvidenceSource {
    static STAGE_15_VERIFICATION = EVIDENCE_SOURCES.STAGE_15_VERIFICATION;
    static STAGE_16_SYMBOLIC = EVIDENCE_SOURCES.STAGE_16_SYMBOLIC;
    static STAGE_17_TESTING = EVIDENCE_SOURCES.STAGE_17_TESTING;
    static STAGE_18_CONCOLIC = EVIDENCE_SOURCES.STAGE_18_CONCOLIC;
    static STAGE_19_REPAIR = EVIDENCE_SOURCES.STAGE_19_REPAIR;
    static STAGE_20_MUTATION = EVIDENCE_SOURCES.STAGE_20_MUTATION;
    static STAGE_21_REGRESSION = EVIDENCE_SOURCES.STAGE_21_REGRESSION;
    static STAGE_22_SPECIFICATION = EVIDENCE_SOURCES.STAGE_22_SPECIFICATION;
    static STAGE_23_EXPLORATION = EVIDENCE_SOURCES.STAGE_23_EXPLORATION;
    static STAGE_24_PROBABILISTIC = EVIDENCE_SOURCES.STAGE_24_PROBABILISTIC;
    static RUNTIME_EXECUTION = EVIDENCE_SOURCES.RUNTIME_EXECUTION;
    static TEST_EXECUTION = EVIDENCE_SOURCES.TEST_EXECUTION;
    static USER_INTERACTION = EVIDENCE_SOURCES.USER_INTERACTION;
    static ENVIRONMENT = EVIDENCE_SOURCES.ENVIRONMENT;

    static isValid(source) {
        return Object.values(EVIDENCE_SOURCES).includes(source);
    }
}
