export const UncertaintyKind = Object.freeze({
  OBSERVATIONAL: 'OBSERVATIONAL',
  STATISTICAL: 'STATISTICAL',
  ENVIRONMENTAL: 'ENVIRONMENTAL',
  NONDETERMINISM: 'NONDETERMINISM',
  MODEL: 'MODEL',
  SPECIFICATION: 'SPECIFICATION',
  ORACLE: 'ORACLE',
  EXECUTION: 'EXECUTION',
  ANALYSIS: 'ANALYSIS',
  UNKNOWN: 'UNKNOWN'
});
