/**
 * EngineeringHealthDimension.js
 * Enumerates inspectable dimensions of engineering health.
 */

export const EngineeringHealthDimension = Object.freeze({
  CORRECTNESS: 'CORRECTNESS',
  SECURITY: 'SECURITY',
  PERFORMANCE: 'PERFORMANCE',
  RELIABILITY: 'RELIABILITY',
  CONCURRENCY: 'CONCURRENCY',
  ARCHITECTURE: 'ARCHITECTURE',
  MAINTAINABILITY: 'MAINTAINABILITY',
  TEST_ADEQUACY: 'TEST_ADEQUACY',
  VERIFICATION_COVERAGE: 'VERIFICATION_COVERAGE',
  CHANGE_SAFETY: 'CHANGE_SAFETY',
  SPECIFICATION_COVERAGE: 'SPECIFICATION_COVERAGE',
  TECHNICAL_DEBT: 'TECHNICAL_DEBT',
  VERIFICATION_DEBT: 'VERIFICATION_DEBT'
});
