/**
 * ProjectEntityKind.js
 * Comprehensive enum of all project entity kinds recognized by ProViz.
 */

export const ProjectEntityKind = Object.freeze({
  REPOSITORY: 'REPOSITORY',
  APPLICATION: 'APPLICATION',
  PACKAGE: 'PACKAGE',
  MODULE: 'MODULE',
  FILE: 'FILE',
  SYMBOL: 'SYMBOL',
  API: 'API',
  DEPENDENCY: 'DEPENDENCY',
  TEST: 'TEST',
  SPECIFICATION: 'SPECIFICATION',
  VERIFICATION_OBLIGATION: 'VERIFICATION_OBLIGATION',
  SECURITY_BOUNDARY: 'SECURITY_BOUNDARY',
  PERFORMANCE_MODEL: 'PERFORMANCE_MODEL',
  CONCURRENCY_MODEL: 'CONCURRENCY_MODEL',
  TRANSFORMATION: 'TRANSFORMATION',
  EVIDENCE: 'EVIDENCE'
});
