/**
 * RecommendationKind.js
 * Enumerates categories of actionable engineering and architecture recommendations.
 */

export const RecommendationKind = Object.freeze({
  REFACTOR: 'REFACTOR',
  ADD_TESTS: 'ADD_TESTS',
  ADD_CONTRACT: 'ADD_CONTRACT',
  ADD_SECURITY_VERIFICATION: 'ADD_SECURITY_VERIFICATION',
  REDUCE_COUPLING: 'REDUCE_COUPLING',
  BREAK_DEPENDENCY_CYCLE: 'BREAK_DEPENDENCY_CYCLE',
  REPAIR_ARCHITECTURE_DRIFT: 'REPAIR_ARCHITECTURE_DRIFT',
  INCREASE_PERFORMANCE_COVERAGE: 'INCREASE_PERFORMANCE_COVERAGE',
  EXPLORE_CONCURRENCY: 'EXPLORE_CONCURRENCY',
  REDUCE_VERIFICATION_DEBT: 'REDUCE_VERIFICATION_DEBT',
  UPDATE_SPECIFICATION: 'UPDATE_SPECIFICATION',
  REVIEW_HIGH_RISK_COMPONENT: 'REVIEW_HIGH_RISK_COMPONENT'
});
