/**
 * PropertyKind — Canonical enumeration of verifiable program properties.
 */

export const PROPERTY_KINDS = Object.freeze({
    NON_NULL: 'NON_NULL',
    NULL: 'NULL',
    TYPE_IS: 'TYPE_IS',
    TYPE_MAY_BE: 'TYPE_MAY_BE',
    VALUE_EQUALS: 'VALUE_EQUALS',
    VALUE_IN_RANGE: 'VALUE_IN_RANGE',
    INDEX_IN_BOUNDS: 'INDEX_IN_BOUNDS',
    ATTRIBUTE_EXISTS: 'ATTRIBUTE_EXISTS',
    CALLABLE: 'CALLABLE',
    DIVISOR_NON_ZERO: 'DIVISOR_NON_ZERO',
    BRANCH_REACHABLE: 'BRANCH_REACHABLE',
    BRANCH_UNREACHABLE: 'BRANCH_UNREACHABLE',
    LOOP_TERMINATES: 'LOOP_TERMINATES',
    LOOP_MAY_NOT_TERMINATE: 'LOOP_MAY_NOT_TERMINATE',
    RETURN_REACHED: 'RETURN_REACHED',
    EXCEPTION_REACHED: 'EXCEPTION_REACHED',
    MUTATION_REACHABLE: 'MUTATION_REACHABLE',
    ALIAS_EXISTS: 'ALIAS_EXISTS',
    COLLECTION_ELEMENT_TYPE: 'COLLECTION_ELEMENT_TYPE',
    FUNCTION_ARGUMENT_COMPATIBLE: 'FUNCTION_ARGUMENT_COMPATIBLE',
    RETURN_TYPE_COMPATIBLE: 'RETURN_TYPE_COMPATIBLE',
});
