/**
 * Verification Agent Kinds
 */
export const VerificationAgentKind = Object.freeze({
  STATIC_ANALYZER: 'STATIC_ANALYZER',
  SYMBOLIC_SOLVER: 'SYMBOLIC_SOLVER',
  CONCOLIC_ENGINE: 'CONCOLIC_ENGINE',
  TEST_GENERATOR: 'TEST_GENERATOR',
  TEST_EXECUTOR: 'TEST_EXECUTOR',
  MUTATION_ENGINE: 'MUTATION_ENGINE',
  REPAIR_ENGINE: 'REPAIR_ENGINE',
  REGRESSION_ENGINE: 'REGRESSION_ENGINE',
  PROBABILISTIC_ENGINE: 'PROBABILISTIC_ENGINE',
  ORACLE_ENGINE: 'ORACLE_ENGINE',
  CONTRACT_ENGINE: 'CONTRACT_ENGINE',
  INVARIANT_ENGINE: 'INVARIANT_ENGINE',
  LANGUAGE_ANALYZER: 'LANGUAGE_ANALYZER',
  RUNTIME_ANALYZER: 'RUNTIME_ANALYZER',
  EXTERNAL_SOLVER: 'EXTERNAL_SOLVER'
});
