/**
 * ExplorationKind — Canonical taxonomy of exploration techniques.
 */

export const ExplorationKind = Object.freeze({
    PROPERTY_BASED: 'PROPERTY_BASED',
    BOUNDARY: 'BOUNDARY',
    RANDOMIZED: 'RANDOMIZED',
    GRAMMAR_GUIDED: 'GRAMMAR_GUIDED',
    STRUCTURED: 'STRUCTURED',
    METAMORPHIC: 'METAMORPHIC',
    COVERAGE_GUIDED: 'COVERAGE_GUIDED',
    SPECIFICATION_GUIDED: 'SPECIFICATION_GUIDED',
    ORACLE_GUIDED: 'ORACLE_GUIDED',
    MUTATION_GUIDED: 'MUTATION_GUIDED',
    REGRESSION_GUIDED: 'REGRESSION_GUIDED',
    PATH_GUIDED: 'PATH_GUIDED',
    STATE_GUIDED: 'STATE_GUIDED',
    TRANSITION_GUIDED: 'TRANSITION_GUIDED',
    BEHAVIOR_DIVERSITY: 'BEHAVIOR_DIVERSITY',
    NOVELTY_GUIDED: 'NOVELTY_GUIDED',
    COUNTEREXAMPLE_GUIDED: 'COUNTEREXAMPLE_GUIDED',
    ADAPTIVE: 'ADAPTIVE',
    HYBRID: 'HYBRID',
});
