export const ExplorationFindingKind = Object.freeze({
  DISCOVERED_NEW_BEHAVIOR: 'DISCOVERED_NEW_BEHAVIOR',
  VIOLATED_METAMORPHIC_RELATION: 'VIOLATED_METAMORPHIC_RELATION',
  KILLED_SURVIVING_MUTANT: 'KILLED_SURVIVING_MUTANT',
  CLOSED_SPECIFICATION_GAP: 'CLOSED_SPECIFICATION_GAP',
  CONFLICTING_BEHAVIOR: 'CONFLICTING_BEHAVIOR',
  DISCOVERED_CRASH_OR_EXCEPTION: 'DISCOVERED_CRASH_OR_EXCEPTION',
  DISCOVERED_BOUNDARY_VIOLATION: 'DISCOVERED_BOUNDARY_VIOLATION',
  MINIMIZED_COUNTEREXAMPLE: 'MINIMIZED_COUNTEREXAMPLE'
});
