/**
 * ExplorationStrategy — High-level exploration scheduling and generation strategies.
 */

export const ExplorationStrategy = Object.freeze({
    UNIFORM: 'UNIFORM',
    BOUNDARY_FIRST: 'BOUNDARY_FIRST',
    COVERAGE_DRIVEN: 'COVERAGE_DRIVEN',
    SPECIFICATION_GAP_DRIVEN: 'SPECIFICATION_GAP_DRIVEN',
    MUTATION_TARGETED: 'MUTATION_TARGETED',
    REGRESSION_FOCUSED: 'REGRESSION_FOCUSED',
    METAMORPHIC_PERTURBATION: 'METAMORPHIC_PERTURBATION',
    NOVELTY_MAXIMIZING: 'NOVELTY_MAXIMIZING',
    ADAPTIVE_FEEDBACK: 'ADAPTIVE_FEEDBACK',
    HYBRID: 'HYBRID',
});
