export const InputMutationOperator = Object.freeze({
  INCREMENT: 'INCREMENT',
  DECREMENT: 'DECREMENT',
  NEGATE: 'NEGATE',
  ZERO: 'ZERO',
  BOUNDARY_SNAP: 'BOUNDARY_SNAP',
  STRING_INSERT: 'STRING_INSERT',
  STRING_DELETE: 'STRING_DELETE',
  STRING_REPLACE: 'STRING_REPLACE',
  STRING_TRUNCATE: 'STRING_TRUNCATE',
  ARRAY_APPEND: 'ARRAY_APPEND',
  ARRAY_POP: 'ARRAY_POP',
  ARRAY_SHUFFLE: 'ARRAY_SHUFFLE',
  ARRAY_REVERSE: 'ARRAY_REVERSE',
  STRUCT_NULLIFY: 'STRUCT_NULLIFY',
  STRUCT_MUTATE_KEY: 'STRUCT_MUTATE_KEY'
});
