export const EvidenceGapKind = Object.freeze({
  MISSING_PROOF: 'MISSING_PROOF',
  MISSING_COVERAGE: 'MISSING_COVERAGE',
  MISSING_COUNTEREXAMPLE: 'MISSING_COUNTEREXAMPLE',
  MISSING_ORACLE: 'MISSING_ORACLE',
  MISSING_OBSERVATION: 'MISSING_OBSERVATION',
  STALE_EVIDENCE: 'STALE_EVIDENCE',
  CONFLICTING_EVIDENCE: 'CONFLICTING_EVIDENCE',
  INSUFFICIENT_SAMPLE: 'INSUFFICIENT_SAMPLE',
  SURVIVING_MUTANT: 'SURVIVING_MUTANT',
  UNEXPLORED_PATH: 'UNEXPLORED_PATH',
  UNVALIDATED_REPAIR: 'UNVALIDATED_REPAIR',
  ENVIRONMENT_MISMATCH: 'ENVIRONMENT_MISMATCH',
  SPECIFICATION_UNCERTAINTY: 'SPECIFICATION_UNCERTAINTY'
});
