export const ExperimentKind = Object.freeze({
  STATIC_VERIFY: 'STATIC_VERIFY',
  SYMBOLIC_PROVE: 'SYMBOLIC_PROVE',
  SYMBOLIC_DISPROVE: 'SYMBOLIC_DISPROVE',
  GENERATE_TEST: 'GENERATE_TEST',
  EXECUTE_TEST: 'EXECUTE_TEST',
  CONCOLIC_EXPLORE: 'CONCOLIC_EXPLORE',
  MUTATION_CAMPAIGN: 'MUTATION_CAMPAIGN',
  KILL_MUTANT: 'KILL_MUTANT',
  VALIDATE_REPAIR: 'VALIDATE_REPAIR',
  REGRESSION_RUN: 'REGRESSION_RUN',
  REPEAT_OBSERVATION: 'REPEAT_OBSERVATION',
  ANOMALY_REPRODUCTION: 'ANOMALY_REPRODUCTION',
  BOUNDARY_EXPLORATION: 'BOUNDARY_EXPLORATION',
  ORACLE_VALIDATION: 'ORACLE_VALIDATION',
  CONTRACT_CHECK: 'CONTRACT_CHECK',
  INVARIANT_CHECK: 'INVARIANT_CHECK'
});
