export const PlanningReason = Object.freeze({
  HIGH_UNCERTAINTY: 'HIGH_UNCERTAINTY',
  HIGH_RISK: 'HIGH_RISK',
  HIGH_INFORMATION_GAIN: 'HIGH_INFORMATION_GAIN',
  LOW_COST: 'LOW_COST',
  UNEXPLORED_BRANCH: 'UNEXPLORED_BRANCH',
  SURVIVING_MUTANT: 'SURVIVING_MUTANT',
  STALE_EVIDENCE: 'STALE_EVIDENCE',
  CONFLICTING_EVIDENCE: 'CONFLICTING_EVIDENCE',
  FORMAL_PROOF_UNAVAILABLE: 'FORMAL_PROOF_UNAVAILABLE'
});
