export const PlanningTermination = Object.freeze({
  COMPLETE: 'COMPLETE',
  PARTIAL: 'PARTIAL',
  BLOCKED: 'BLOCKED',
  BUDGET_EXHAUSTED: 'BUDGET_EXHAUSTED',
  TIMEOUT: 'TIMEOUT',
  UNRESOLVED: 'UNRESOLVED'
});

export const StoppingReasonKind = Object.freeze({
  ALL_GOALS_SATISFIED: 'ALL_GOALS_SATISFIED',
  CONFIDENCE_THRESHOLD: 'CONFIDENCE_THRESHOLD',
  UNCERTAINTY_THRESHOLD: 'UNCERTAINTY_THRESHOLD',
  RISK_THRESHOLD: 'RISK_THRESHOLD',
  NO_ACTIONABLE_GAPS: 'NO_ACTIONABLE_GAPS',
  BUDGET_EXHAUSTED: 'BUDGET_EXHAUSTED',
  NO_INFORMATION_GAIN: 'NO_INFORMATION_GAIN',
  TIMEOUT: 'TIMEOUT',
  MAX_ITERATIONS: 'MAX_ITERATIONS',
  FORMAL_PROOF_OBTAINED: 'FORMAL_PROOF_OBTAINED'
});
