export const ReplanningTrigger = Object.freeze({
  SOURCE_CHANGED: 'SOURCE_CHANGED',
  TEST_CHANGED: 'TEST_CHANGED',
  SPEC_CHANGED: 'SPEC_CHANGED',
  ORACLE_CHANGED: 'ORACLE_CHANGED',
  DEPENDENCY_CHANGED: 'DEPENDENCY_CHANGED',
  ENVIRONMENT_CHANGED: 'ENVIRONMENT_CHANGED',
  REPAIR_APPLIED: 'REPAIR_APPLIED',
  REPAIR_REVERTED: 'REPAIR_REVERTED',
  MUTATION_SURVIVED: 'MUTATION_SURVIVED',
  NEW_FINDING: 'NEW_FINDING',
  NEW_ANOMALY: 'NEW_ANOMALY',
  CONFIDENCE_DROP: 'CONFIDENCE_DROP',
  EVIDENCE_STALE: 'EVIDENCE_STALE'
});
