export const VerificationGoalKind = Object.freeze({
  PROPERTY: 'PROPERTY',
  FINDING: 'FINDING',
  PATH: 'PATH',
  BRANCH: 'BRANCH',
  CONTRACT: 'CONTRACT',
  INVARIANT: 'INVARIANT',
  SPECIFICATION: 'SPECIFICATION',
  TEST_ADEQUACY: 'TEST_ADEQUACY',
  MUTATION_SURVIVOR: 'MUTATION_SURVIVOR',
  REGRESSION: 'REGRESSION',
  ANOMALY: 'ANOMALY',
  RARE_BEHAVIOR: 'RARE_BEHAVIOR',
  ORACLE: 'ORACLE',
  UNCERTAINTY: 'UNCERTAINTY',
  RISK: 'RISK',
  COVERAGE: 'COVERAGE'
});
