export const VerificationGoalStatus = Object.freeze({
  UNSTARTED: 'UNSTARTED',
  PLANNED: 'PLANNED',
  IN_PROGRESS: 'IN_PROGRESS',
  SATISFIED: 'SATISFIED',
  PARTIALLY_SATISFIED: 'PARTIALLY_SATISFIED',
  BLOCKED: 'BLOCKED',
  FAILED: 'FAILED',
  STALE: 'STALE',
  INVALIDATED: 'INVALIDATED'
});
