/**
 * SecurityPropertyKind.js
 * Canonical security and safety property classifications in ProViz Stage 31.
 */

export const SecurityPropertyKind = Object.freeze({
  CONFIDENTIALITY: 'CONFIDENTIALITY',
  INTEGRITY: 'INTEGRITY',
  AUTHENTICITY: 'AUTHENTICITY',
  AVAILABILITY: 'AVAILABILITY',
  AUTHORIZATION: 'AUTHORIZATION',
  AUTHENTICATION: 'AUTHENTICATION',
  NON_REPUDIATION: 'NON_REPUDIATION',
  LEAST_PRIVILEGE: 'LEAST_PRIVILEGE',
  ISOLATION: 'ISOLATION',
  SECURE_DEFAULT: 'SECURE_DEFAULT',
  INPUT_VALIDATION: 'INPUT_VALIDATION',
  OUTPUT_SAFETY: 'OUTPUT_SAFETY',
  RESOURCE_SAFETY: 'RESOURCE_SAFETY',
  MEMORY_SAFETY: 'MEMORY_SAFETY',
  INFORMATION_FLOW: 'INFORMATION_FLOW'
});
