/**
 * Explicit Causal Relationship Classifications
 */
export const CausalRelationKind = Object.freeze({
  DIRECT_CAUSE: 'DIRECT_CAUSE',
  INDIRECT_CAUSE: 'INDIRECT_CAUSE',
  ENABLING_CONDITION: 'ENABLING_CONDITION',
  NECESSARY_CONDITION: 'NECESSARY_CONDITION',
  SUFFICIENT_CONDITION: 'SUFFICIENT_CONDITION',
  CONTRIBUTING_FACTOR: 'CONTRIBUTING_FACTOR',
  TRIGGER: 'TRIGGER',
  BLOCKER: 'BLOCKER',
  PRECONDITION: 'PRECONDITION',
  POSTCONDITION: 'POSTCONDITION',
  CAUSAL_CHAIN: 'CAUSAL_CHAIN',
  UNKNOWN_CAUSALITY: 'UNKNOWN_CAUSALITY'
});
