/**
 * OracleKind — Taxonomy of test oracle evaluation kinds.
 */

export const OracleKind = Object.freeze({
    RETURN_VALUE: 'RETURN_VALUE',
    RETURN_RELATION: 'RETURN_RELATION',
    EXCEPTION_TYPE: 'EXCEPTION_TYPE',
    EXCEPTION_ABSENCE: 'EXCEPTION_ABSENCE',
    STATE_PROPERTY: 'STATE_PROPERTY',
    HEAP_PROPERTY: 'HEAP_PROPERTY',
    OBJECT_PROPERTY: 'OBJECT_PROPERTY',
    WATCH_VALUE: 'WATCH_VALUE',
    TYPE_PROPERTY: 'TYPE_PROPERTY',
    RANGE_PROPERTY: 'RANGE_PROPERTY',
    COLLECTION_PROPERTY: 'COLLECTION_PROPERTY',
    TRACE_PROPERTY: 'TRACE_PROPERTY',
    PATH_PROPERTY: 'PATH_PROPERTY',
    TEMPORAL_PROPERTY: 'TEMPORAL_PROPERTY',
    CUSTOM_DECLARED: 'CUSTOM_DECLARED',
});
