/**
 * SpecificationSource — Provenance and origin source of a specification.
 */

export const SpecificationSource = Object.freeze({
    STATIC_ANALYSIS: 'STATIC_ANALYSIS',
    RUNTIME_OBSERVATION: 'RUNTIME_OBSERVATION',
    TEST_ASSERTION: 'TEST_ASSERTION',
    WATCH_EXPRESSION: 'WATCH_EXPRESSION',
    SYMBOLIC_PROOF: 'SYMBOLIC_PROOF',
    SYMBOLIC_COUNTEREXAMPLE: 'SYMBOLIC_COUNTEREXAMPLE',
    CONCOLIC_EXECUTION: 'CONCOLIC_EXECUTION',
    MUTATION_ANALYSIS: 'MUTATION_ANALYSIS',
    REPAIR_VALIDATION: 'REPAIR_VALIDATION',
    REGRESSION_ANALYSIS: 'REGRESSION_ANALYSIS',
    USER_DECLARED: 'USER_DECLARED',
});
