/**
 * SpecificationKind — Canonical enum of specification types.
 */

export const SpecificationKind = Object.freeze({
    PRECONDITION: 'PRECONDITION',
    POSTCONDITION: 'POSTCONDITION',
    INVARIANT: 'INVARIANT',
    STATE_TRANSITION: 'STATE_TRANSITION',
    RETURN_PROPERTY: 'RETURN_PROPERTY',
    EXCEPTION_PROPERTY: 'EXCEPTION_PROPERTY',
    TYPE_PROPERTY: 'TYPE_PROPERTY',
    NULLABILITY_PROPERTY: 'NULLABILITY_PROPERTY',
    RANGE_PROPERTY: 'RANGE_PROPERTY',
    COLLECTION_PROPERTY: 'COLLECTION_PROPERTY',
    OBJECT_PROPERTY: 'OBJECT_PROPERTY',
    ALIAS_PROPERTY: 'ALIAS_PROPERTY',
    MUTATION_PROPERTY: 'MUTATION_PROPERTY',
    RELATIONAL_PROPERTY: 'RELATIONAL_PROPERTY',
    TEMPORAL_PROPERTY: 'TEMPORAL_PROPERTY',
    CONTROL_FLOW_PROPERTY: 'CONTROL_FLOW_PROPERTY',
    DATAFLOW_PROPERTY: 'DATAFLOW_PROPERTY',
    SECURITY_PROPERTY: 'SECURITY_PROPERTY',
    REGRESSION_PROPERTY: 'REGRESSION_PROPERTY',
});
