/**
 * TestObjectiveKind — Canonical taxonomy of test objectives.
 */

export const TestObjectiveKind = Object.freeze({
    COVER_BRANCH: 'COVER_BRANCH',
    COVER_PATH: 'COVER_PATH',
    VIOLATE_PROPERTY: 'VIOLATE_PROPERTY',
    CONFIRM_PROPERTY: 'CONFIRM_PROPERTY',
    DISTINGUISH_BEHAVIOR: 'DISTINGUISH_BEHAVIOR',
    EXERCISE_EXCEPTION: 'EXERCISE_EXCEPTION',
    EXERCISE_BOUNDARY: 'EXERCISE_BOUNDARY',
    EXERCISE_ALIAS: 'EXERCISE_ALIAS',
    EXERCISE_MUTATION: 'EXERCISE_MUTATION',
    VALIDATE_REPAIR: 'VALIDATE_REPAIR',
    VALIDATE_REGRESSION: 'VALIDATE_REGRESSION',
    CONFIRM_ORACLE: 'CONFIRM_ORACLE',
    EXPLORE_UNKNOWN_REGION: 'EXPLORE_UNKNOWN_REGION',
});
