/**
 * TransformationKind.js
 * Canonical transformation categories for software evolution and verified refactoring.
 */

export const TransformationKind = Object.freeze({
  // Symbol & Variable Level
  RENAME_SYMBOL: 'RENAME_SYMBOL',
  MOVE_SYMBOL: 'MOVE_SYMBOL',
  EXTRACT_FUNCTION: 'EXTRACT_FUNCTION',
  INLINE_FUNCTION: 'INLINE_FUNCTION',
  EXTRACT_VARIABLE: 'EXTRACT_VARIABLE',
  INLINE_VARIABLE: 'INLINE_VARIABLE',

  // Signature & Visibility
  CHANGE_SIGNATURE: 'CHANGE_SIGNATURE',
  CHANGE_RETURN_TYPE: 'CHANGE_RETURN_TYPE',
  CHANGE_PARAMETER: 'CHANGE_PARAMETER',
  CHANGE_VISIBILITY: 'CHANGE_VISIBILITY',

  // Control Flow & Conditionals
  RESTRUCTURE_CONDITIONAL: 'RESTRUCTURE_CONDITIONAL',
  SIMPLIFY_CONDITIONAL: 'SIMPLIFY_CONDITIONAL',
  MERGE_CONDITIONAL: 'MERGE_CONDITIONAL',
  SPLIT_CONDITIONAL: 'SPLIT_CONDITIONAL',

  // Loops & Iterations
  LOOP_REFACTOR: 'LOOP_REFACTOR',
  LOOP_TO_ITERATION: 'LOOP_TO_ITERATION',
  ITERATION_TO_LOOP: 'ITERATION_TO_LOOP',

  // Data Structures & Algorithms
  DATA_STRUCTURE_REPLACEMENT: 'DATA_STRUCTURE_REPLACEMENT',
  ALGORITHM_REPLACEMENT: 'ALGORITHM_REPLACEMENT',

  // Architecture & Modularity
  MODULE_SPLIT: 'MODULE_SPLIT',
  MODULE_MERGE: 'MODULE_MERGE',
  PACKAGE_RESTRUCTURE: 'PACKAGE_RESTRUCTURE',

  // API & Interfaces
  API_REDESIGN: 'API_REDESIGN',
  INTERFACE_REFACTOR: 'INTERFACE_REFACTOR',

  // Dependencies & Resources
  DEPENDENCY_REPLACEMENT: 'DEPENDENCY_REPLACEMENT',
  RESOURCE_LIFECYCLE_REFACTOR: 'RESOURCE_LIFECYCLE_REFACTOR',

  // Errors & Exceptions
  EXCEPTION_HANDLING_REFACTOR: 'EXCEPTION_HANDLING_REFACTOR',
  ERROR_PROPAGATION_REFACTOR: 'ERROR_PROPAGATION_REFACTOR',

  // Concurrency & Memory
  CONCURRENCY_REFACTOR: 'CONCURRENCY_REFACTOR',
  MEMORY_REFACTOR: 'MEMORY_REFACTOR',

  // Quality & Hardening
  PERFORMANCE_TRANSFORMATION: 'PERFORMANCE_TRANSFORMATION',
  SECURITY_HARDENING: 'SECURITY_HARDENING',

  // Contracts & Specifications
  SPECIFICATION_STRENGTHENING: 'SPECIFICATION_STRENGTHENING',
  CONTRACT_PRESERVING_TRANSFORMATION: 'CONTRACT_PRESERVING_TRANSFORMATION',

  // Extensible Custom
  CUSTOM: 'CUSTOM'
});
